version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
      - order1
      - order2
      - payment1
      - payment2
    networks:
      - lb-network
      - api-network

  app1:
    build: .
    container_name: app1
    expose:
      - "3000"
    depends_on:
      - redis
    networks:
      - lb-network

  app2:
    build: .
    container_name: app2
    expose:
      - "3000"
    depends_on:
      - redis
    networks:
      - lb-network

  app3:
    build: .
    container_name: app3
    expose:
      - "3000"
    depends_on:
      - redis
    networks:
      - lb-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - lb-network

  order1:
    build: ./microservices/order
    container_name: order1
    expose:
      - "3000"
    networks:
      - api-network

  order2:
    build: ./microservices/order
    container_name: order2
    expose:
      - "3000"
    networks:
      - api-network

  payment1:
    build: ./microservices/payment
    container_name: payment1
    expose:
      - "3000"
    networks:
      - api-network

  payment2:
    build: ./microservices/payment
    container_name: payment2
    expose:
      - "3000"
    networks:
      - api-network

networks:
  lb-network:
    driver: bridge
  api-network:
    driver: bridge
