events {}

http {
  upstream backend_servers {
    server app1:3000;
    server app2:3000;
    server app3:3000;
  }

  # ORDER SERVICE (load balanced)
  upstream order_service {
    server order1:3000;
    server order2:3000;
  }

  # PAYMENT SERVICE (load balanced)
  upstream payment_service {
    server payment1:3000;
    server payment2:3000;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://backend_servers;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    
    # Order service routes
    location /order {
      proxy_pass http://order_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    
    # Payment service routes
    location /payment {
      proxy_pass http://payment_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
